stages:
  - check
  - build
  - target_test
  - deploy

variables:
  # Versioned esp-idf-doc env image to use for all document building jobs
  ESP_DOCS_ENV_IMAGE: "$CI_DOCKER_REGISTRY/esp-idf-doc-env-v5.3:1-1"
  ESP_SR_PATH: "$CI_PROJECT_DIR"
  BATCH_BUILD: "1"
  V: "0"
  IDF_CI_BUILD: "1"
  DOCKER_TARGET_TEST_ENV_IMAGE: "$CI_DOCKER_REGISTRY/target-test-env-v5.3:1"

before_script:
  # add gitlab ssh key
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo -n $GITLAB_KEY > ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git --version
  - git submodule update --init --recursive --force
  - pip install idf_build_apps

include:
  - local: .gitlab/ci/rules.yml
  - local: .gitlab/ci/pre_check.yml
  - local: .gitlab/ci/build.yml
  - local: .gitlab/ci/target_test.yml
  - local: .gitlab/ci/deploy.yml